name: HealthCheckIn

on:
  push:
    branches:
      - master
  watch:
    types: started
  workflow_dispatch:
  schedule:
  # 2am & 23am UTC correspond to 10am & 7am
    - cron: 0 2,23 * * *

jobs:
  HealthCheckIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    strategy:
      matrix:
        include:
          - username: ACCOUNT
            password: PASSWORD
          - username: ACCOUNT2
            password: PASSWORD2
          - username: ACCOUNT3
            password: PASSWORD3
          - username: ACCOUNT4
            password: PASSWORD4
          - username: ACCOUNT5
            password: PASSWORD5
          - username: ACCOUNT6
            password: PASSWORD6
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets[matrix.username] }}
          PASSWORD: ${{ secrets[matrix.password] }}
        run: |
          python3 check-in.py ${ACCOUNT} ${PASSWORD}
