name: ClockIn

on:
  push:
    branches:
      - master
  watch:
    types: started
  workflow_dispatch:
  schedule:
    - cron: 0 */8 * * *

jobs:
  ClockIn:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    matrix:
      include:
        - username: ACCOUNT
          password: PASSWORD
        - username: ACCOUNT2
          password: PASSWORD2
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Python
        uses: actions/setup-python@v3.1.0
        with:
          python-version: 3.9
      - name: Install packages
        run: |
          pip3 install requests
          pip3 install ddddocr
      - name: Clock In
        env:
          ACCOUNT: ${{ secrets[matrix.username] }}
          PASSWORD: ${{ secrets[matrix.password] }}
        run: |
          python3 check-in.py ${ACCOUNT} ${PASSWORD}
